name: Publish NPM package

on:
  push:
    tags:
      - "*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Build
        run: API_BASEPATH=$API_BASEPATH make build
        env:
          API_BASEPATH: ${{ env.API_BASEPATH }}
      - name: Publish package
        run: |
          cd pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

